### PR TITLE
Feature user services

### LINKED ISSUE #1: Make the user service class
We have no user service class!

### PR DESCRIPTION
**Pull request by miiwo**
Implements a simple back end user service.

### CODE REVIEW

**Comment by Mark1Zhu** [comment]
Need to remove the 'db' folder 
Otherwise LGTM

**Review by SooysC — CHANGES_REQUESTED** [review]
smh not good

**Review by SooysC — APPROVED** [review]

**Review by Mark1Zhu — APPROVED** [review]
5/7

**Review by SooysC — APPROVED** [review]
good good

**Review by SooysC — APPROVED** [review]
good good

**Pull request merged**
